### ISSUE TITLE
Project is not maintained anymore. May I take it over?

### ISSUE THREAD

**Issue by jankal** [payden/php-xz#11]
As I see, there is nobody maintinaing this repo since 2013. Probably it needs new power...

**Comment by timgws** [comment]
@jankal this is open source land! If something is not maintained, fork it, maintain it, and become the php-xz by default 👍 

There is no reason for @payden to say yes to your request, he won't be able to see any of the previous work that you have done on `php-xz` (at least I can't see any in the commit history).

**Comment by jankal** [comment]
OK sure. I do just have the problem to need this somewhere else. That's why I wanted to know if I could take it over and fix the major bugs for it (I don't expect any merges here after that long unmaintained period) to be compatible with PHP7 and stuff.

So it's just a simple need for me. I don't have contributed anything to this repo yet than helped someone with their issue.

But sure. I'll fork it. I saw it would be good to fork udan11/php-xz being the one ahead of payden/php-xz the most.

**Comment by ToBeFree** [comment]
Thank you very much for bringing new life to this feature. :)

**Comment by timgws** [comment]
👍 awesome work @jankal  :)
